### ISSUE TITLE
Not working with Angular AOT

### ISSUE THREAD

**Issue by dgwaldo** [spali/ng2-movable#10]
Looks like a simple tweak to output *.metadata.json with your NPM package would fix this.
Here is an article on AOT.

https://blog.angularindepth.com/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5

**Comment by spali** [comment]
Could you please test the dev version 0.3.0.
because of the complete redesign (not the module itself, but the project there shouldn't be new bugs, but probably the project setup could contain bugs.
So please test and give feedback.

**Comment by spali** [comment]
due no feedback, I close this issue
