### ISSUE TITLE
Dont working with @angular/cli:1.61

### ISSUE THREAD

**Issue by kotuwe** [spali/ng2-movable#11]
Hello!
Very good module, but with @angular/cli:1.61 have error:

`ERROR in Error: MovableModule is not an NgModule`

**Comment by spali** [comment]
Could you please test the dev version 0.3.0.
because of the complete redesign (not the module itself, but the project there shouldn't be new bugs, but probably the project setup could contain bugs.
So please test and give feedback.

**Comment by spali** [comment]
due no feedback, I close this issue
