### ISSUE TITLE
Angular Update Deprecation warning

### ISSUE THREAD

**Issue by dgwaldo** [spali/ng2-movable#12]
movable.directive.js:250 [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

**Comment by spali** [comment]
I'm working anyway on a complete rework of the project. Will drop usage of /deep/ with it.

**Comment by spali** [comment]
should be solved with version 0.3.0 (currently tagged as `dev` in npm)
because of the complete redesign (not the module itself, but the project there shouldn't be new bugs, but probably the project setup could contain bugs.
So please test and give feedback.
