### ISSUE TITLE
How to use.

### ISSUE THREAD

**Issue by thegeett** [spali/ng2-movable#13]
I am new in angular, please let me know how to use this , I did 
npm install ng2-movable@0.3.0 --save

now I can see ng2-movable folder in node_modules folder, then I added below in my app.component.html

<div style="border: 0.2em dotted red; height: 100px; width: 500px;" id="constrainedByElement">
  <div movable [movableEnabled]="toggle" movableConstraint="constrainedByElement">
    <div><b>Movable constrained to an element</b></div>
    This movable won't left the constrained element.
  </div>
</div>

It gives compile time error at <div movable [movableEnabled]="toggle" 

it says 
Can't bind to 'movableEnabled' since it isn't a known property of 'div'.
	- Identifier 'toggle' is not defined. The component declaration, template variable 
	 declarations, and element references do not contain such a member

Please let me know.

**Comment by spali** [comment]
Did you import the module in your app? See example here: https://github.com/spali/ng2-movable/blob/2a307dee32127cabb91c0ed1fa17f72cf5b6c90d/src/client/app/app.module.ts#L9

**Comment by thegeett** [comment]
Below line in app.module.ts, it shows error "Cannot find module './ng2-movable/index'."

import { MovableModule } from './ng2-movable/index';

**Comment by spali** [comment]
That means the path to the module ist wrong, usually you don't use the dot notation and index for a npm module. Please start with a tutorial to learn the basic.
