### ISSUE TITLE
When dom item is offset from upper left, on start of move item jumps by offset

### ISSUE THREAD

**Issue by dgwaldo** [spali/ng2-movable#3]
Start with a box that starts at position relative top=10, left=10.  Add movable directive to the box.  You'll notice that when you grab the drag handle and start moving the item, it will jump by the offset, so that your cursor is positioned 10 by 10 off of the drag handle.

**Comment by dgwaldo** [comment]
More info on this, I've found that if I don't use a class to set the starting position, but actually inline it into the style, the issue goes away.  

style="top: 100px; left: 25px;"

That get picked up and and then everything works.  I'm not a huge fan of setting inline styles.  Wonder what another simple solution would be?

**Comment by spali** [comment]
I can reproduce this behavior.
Not sure, but it seems, that the initial position of the element is not correctly bound by `HostBinding` at [/src/client/app/ng2-movable/movable.directive.ts#L62-L68](https://github.com/spali/ng2-movable/blob/65a3ba64119f8d2e615d64226393cbe58cd47ee5/src/client/app/ng2-movable/movable.directive.ts#L62-L68)

I very apologize, but currently have not much time to dig into it.
But if you are willing to find the source of the bug, let me know.

**Comment by dgwaldo** [comment]
I believe you're correct in the root cause.  I spent some time trying
different things today and ended up creating a directive to handle
offsetting and stacking my windows as they open.

`
@Directive({
    selector: "[currentWindow]"
})
export class CurrentWindowDirective {

    private _widgetToggleSubscription: Subscription;

    constructor(
        private _clickHandlers: AppClickHandlers,
        private _elementRef: ElementRef
    ) {
        this._widgetToggleSubscription =
_clickHandlers.widgetToggled$.subscribe(t => this.onWindowToggle(t));
    }

    @Input()
    public windowEnum: number;

    private onWindowToggle(toggle: AppComponentEnum) {
        if (toggle === this.windowEnum) {
            this._elementRef.nativeElement.style.zIndex = 20 +
this._clickHandlers.getWindowToggleCount;
            let top = this._elementRef.nativeElement.style.top;
            let left = this._elementRef.nativeElement.style.left;

            // movable (ng2-movable) has issues if direct top and left
style elements aren't set inline.
            // this positions the winow on open.
            if (!top && !left) {
                this._elementRef.nativeElement.style.top =
(this._clickHandlers.getWindowToggleCount * 8) + 50 + "px";
                this._elementRef.nativeElement.style.left =
(this._clickHandlers.getWindowToggleCount * 8) + 15 + "px";
            }

        }
    }
}
`


This just happens to fix the other issue.  ;0)

**Comment by dgwaldo** [comment]
Just thinking about this a little more.  If you apply .css with a style sheet, as I was doing, I don't think the `HostBinding` is going to pick anything up.

**Comment by spali** [comment]
It kept nagging me... 
I have a good and a bad news... the good news is, the above commit fixes your problem. The bad is... it creates a new in other situations (demo app example 3 with nested movable).

**Comment by spali** [comment]
I think I got it.
0.1.2 is published with the fixes.

**Comment by dgwaldo** [comment]
Awesome thanks much.  I'll see if I can find time to work on a way to keep
movable element within a container.
