### ISSUE TITLE
Feature Request: Constraint within Dom Element

### ISSUE THREAD

**Issue by dgwaldo** [spali/ng2-movable#4]
It would be nice to have a feature like this included in the library.

https://jqueryui.com/draggable/#constrain-movement

**Comment by spali** [comment]
I published a dev version on npm `0.2.0-dev` and also updated the demo gh-pages with this version.
Could you please test it a bit on some different browsers you have available.
Currently only have a more or less current chrome and an IE 11.

Hope this suites your needs.
It should also solve most of the positioning bugs I know.
It is now by default constrained to the viewport which makes sense to be in most cases and optionaly allow to be contrained by id to an element and even be disabled with an additional property. 
checkout the demo, should be self explaining.
If you don't report a problem I can publish this as a new regular version this weekend or at least on monday.

**Comment by spali** [comment]
updated https://spali.github.io/ng2-movable/ with 5ede773

**Comment by dgwaldo** [comment]
We've pushed the 0.2.0-dev branch out to our staging app.  So far so good.  I'll keep playing with it, but it was a seamless transition thus far. Thanks again!

**Comment by dgwaldo** [comment]
We did more testing today, still looks good!

**Comment by spali** [comment]
thanks for the feedback. I published the version 0.2.0 finally.
