### ISSUE TITLE
Support for constrain on drop

### ISSUE THREAD

**Issue by davistan** [spali/ng2-movable#7]
Hi Thomas, wonderful library you've created.

Just wondering whether this allows to drop to specific container elements?
Suggest to have features like snap to position, cancel to return to original position, which similar to jqueryUI will be great.

Thanks.

**Comment by spali** [comment]
Hi Davis

This feature is not supported and also not planned to. I try to keep this library as simple as possible. There are a lot of libraries around that support all these fancy drag and drop stuff. This library is more meant to be used i.e. for simple dialogs.
But feel free to build this feature on top of it. If you need something exposed to build a kind of addon, let me know.

regards
Thomas
