### ISSUE TITLE
Firefox Bug: EXCEPTION: t is undefined

### ISSUE THREAD

**Issue by dgwaldo** [spali/ng2-movable#8]
When using ng2-movable in Firefox, an error is encountered.  EXCEPTION: t is undefined.  Perhaps just missing a undefined check.

Here is the stacktrace from Firefox:

c</e.prototype.isEventInHandle@https://spali.github.io/ng2-movable/js/app.js?1494315013034:32:9263
c</e.prototype.startMoving@https://spali.github.io/ng2-movable/js/app.js?1494315013034:32:7836
c</e.prototype.onMouseDown@https://spali.github.io/ng2-movable/js/app.js?1494315013034:32:7500
anonymous/Wrapper_e.prototype.handleEvent@/e/e/wrapper.ngfactory.js:101:21
anonymous/View_t0.prototype.handleEvent_0@/t/t/component.ngfactory.js:73:13
r/<@https://spali.github.io/ng2-movable/js/app.js?1494315013034:17:29912
O</g</t.prototype.invokeTask@https://spali.github.io/ng2-movable/js/shims.js?1494315013031:5:4318
.execute/n</e.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@https://spali.github.io/ng2-movable/js/app.js?1494315013034:32:23842
O</g</t.prototype.invokeTask@https://spali.github.io/ng2-movable/js/shims.js?1494315013031:5:4246
O</v</e.prototype.runTask@https://spali.github.io/ng2-movable/js/shims.js?1494315013031:5:1670
t/this.invoke@https://spali.github.io/ng2-movable/js/shims.js?1494315013031:5:5440

**Comment by spali** [comment]
are you sure this is `t` ? I can reproduce almost the same stack trace but getting `srcElement is undefined`.

**Comment by spali** [comment]
Could you please check if you can reproduce it with the current master? If we mean the same error then it should be fixed with it.

**Comment by spali** [comment]
got it... didn't realize the stacktrace is from the demo on github.io. The minified version renamed the variable. So it was this problem. I published 0.2.1 with the fix and updated the demo.
